name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
        run: curl -s https://portfolio-uscf.onrender.com/ping
